apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    k8s-app: kube-state-metrics
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
      version: v1
  template:
    metadata:
      labels:
        k8s-app: kube-state-metrics
        version: v1
    spec:
      containers:
      - name: kube-state-metrics
        image: dyrnq/kube-state-metrics:v2.9.2
        ports:
        - containerPort: 8181
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.logging"  # Update to match your Elasticsearch host
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"

---

apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging  # Update to match fluentd labels
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kube-state-metrics
    version: v1
  ports:
  - port: 8181
    targetPort: 8181
  type: NodePort
